archives:
  - files:
      - actions.ini
      - babybutton.service
      - README.md
      - LICENSE
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
before:
  hooks:
    - go mod download
builds:
  - binary: '{{ .ProjectName }}'
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - linux
      - windows
    mod_timestamp: '{{ .CommitTimestamp }}'
changelog:
  skip: true
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
env:
  - CGO_ENABLED=0
release:
  github:
    owner: carvers
    name: babybutton
  prerelease: auto
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
